site_name: PlayStation Specifications - psx-spx
site_url: https://psx-spx.consoledev.net/

theme:
  name: material

plugins:
  - search
  - with-pdf:
      output_path: psx-spx.pdf

extra_css:
    - css/extra.css

nav:
    - 'index.md'
    - 'memorymap.md'
    - 'iomap.md'
    - 'graphicsprocessingunitgpu.md'
    - 'geometrytransformationenginegte.md'
    - 'macroblockdecodermdec.md'
    - 'soundprocessingunitspu.md'
    - 'interrupts.md'
    - 'dmachannels.md'
    - 'timers.md'
    - 'cdromdrive.md'
    - 'controllersandmemorycards.md'
    - 'pocketstation.md'
    - 'serialportsio.md'
    - 'expansionportpio.md'
    - 'memorycontrol.md'
    - 'unpredictablethings.md'
    - 'cpuspecifications.md'
    - 'kernelbios.md'
    - 'arcadecabinets.md'
    - 'cheatdevices.md'
    - 'psxdevboardchipsets.md'
    - 'hardwarenumbers.md'
    - 'pinouts.md'
    - 'aboutcredits.md'
    - 'cdromvideocdsvcd.md'
    - 'cdrominternalinfoonpsxcdromcontroller.md'
